fails:Rational#<=> when passed an Object that responds to #coerce does not rescue exception raised in other#coerce
